#!/usr/bin/env python3
"""Bundle the default CustomMetadata records into the packaged static resource.

The Summer '26 platform gack (UNKNOWN_EXCEPTION) on any Metadata API deploy
that contains CustomMetadata *records* means the connector cannot ship
force-app/main/default/customMetadata/ inside the unlocked package. Instead the
records are bundled into the Humanitix_Default_Mappings static resource (this
script) and seeded at install time by HumanitixPostInstall ->
HumanitixMappingSeeder via Metadata.Operations.enqueueDeployment, which is not
affected by the gack. Apex tests load the same resource through
HumanitixDefaultMappings so they exercise the true shipped defaults.

The customMetadata/*.md-meta.xml files remain the source of truth (generated by
generate-default-mappings.py); re-run this script after changing them:

    python3 scripts/dev/generate-mappings-resource.py
"""
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NS = {"md": "http://soap.sforce.com/2006/04/metadata",
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"}

ROOT = Path(__file__).resolve().parents[2]
CMT_DIR = ROOT / "force-app" / "main" / "default" / "customMetadata"
RES_DIR = ROOT / "force-app" / "main" / "default" / "staticresources"
RES_NAME = "Humanitix_Default_Mappings"

META_XML = """<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Private</cacheControl>
    <contentType>application/json</contentType>
    <description>Default Humanitix mapping + sync-setting CustomMetadata records, seeded post-install by HumanitixMappingSeeder. Generated by scripts/dev/generate-mappings-resource.py — do not edit by hand.</description>
</StaticResource>
"""


def typed_value(el):
    if el is None or el.get(f"{{{NS['xsi']}}}nil") == "true":
        return None
    xsi_type = el.get(f"{{{NS['xsi']}}}type", "xsd:string")
    text = el.text or ""
    if xsi_type == "xsd:boolean":
        return text.strip().lower() == "true"
    if xsi_type in ("xsd:double", "xsd:decimal", "xsd:int", "xsd:integer"):
        num = float(text)
        return int(num) if num.is_integer() and xsi_type in ("xsd:int", "xsd:integer") else num
    return text


def parse_record(path: Path):
    full_name = path.name[: -len(".md-meta.xml")]
    type_name, dev_name = full_name.split(".", 1)
    root = ET.parse(path).getroot()
    label_el = root.find("md:label", NS)
    values = {}
    for v in root.findall("md:values", NS):
        field = v.find("md:field", NS).text
        values[field] = typed_value(v.find("md:value", NS))
    return {
        "type": type_name,
        "developerName": dev_name,
        "label": label_el.text if label_el is not None else dev_name,
        "values": dict(sorted(values.items())),
    }


def main():
    files = sorted(CMT_DIR.glob("*.md-meta.xml"))
    if not files:
        sys.exit(f"no CustomMetadata records found in {CMT_DIR}")
    records = [parse_record(p) for p in files]
    records.sort(key=lambda r: (r["type"], r["developerName"]))

    RES_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "comment": "Generated by scripts/dev/generate-mappings-resource.py from "
                   "force-app/main/default/customMetadata/. Do not edit by hand.",
        "records": records,
    }
    (RES_DIR / f"{RES_NAME}.json").write_text(json.dumps(payload, indent=1) + "\n")
    (RES_DIR / f"{RES_NAME}.resource-meta.xml").write_text(META_XML)

    counts = {}
    for r in records:
        counts[r["type"]] = counts.get(r["type"], 0) + 1
    print(f"wrote {RES_DIR / (RES_NAME + '.json')}")
    for t, n in sorted(counts.items()):
        print(f"  {t}: {n}")


if __name__ == "__main__":
    main()
