#!/usr/bin/env python3
"""Generate anonymous-Apex seed scripts for every CustomMetadata record in
force-app/main/default/customMetadata/, working around the Summer '26 platform
gack (UNKNOWN_EXCEPTION) on CustomMetadata record deploys.

Each generated .apex file builds Metadata.CustomMetadata items and enqueues one
Metadata.Operations deployment. Records that other records reference (anything
that is not a Humanitix_Field_Mapping) land in chunk 00 and should be run
first — but Metadata.Operations deployments are asynchronous, so enqueueing
chunk 00 does not mean it has finished: poll the record counts between phases
(see below) before relying on the parent/child relationships being resolvable.

Usage:
    python3 scripts/dev/generate-cmt-seed.py OUT_DIR
    for f in OUT_DIR/seed-*.apex; do sf apex run -f "$f" -o <org>; done
    # poll until: SELECT COUNT() FROM Humanitix_Field_Mapping__mdt == expected
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NS = {"md": "http://soap.sforce.com/2006/04/metadata",
      "xsi": "http://www.w3.org/2001/XMLSchema-instance"}
# executeAnonymous rejects large scripts ("Script too large", ~32KB): keep
# chunks small enough that records * values stays well under the limit.
CHUNK = 12


def apex_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n") + "'"


def parse_record(path: Path):
    root = ET.parse(path).getroot()
    full_name = path.name[: -len(".md-meta.xml")]
    label_el = root.find("md:label", NS)
    label = label_el.text if label_el is not None else full_name
    values = []
    for v in root.findall("md:values", NS):
        field = v.find("md:field", NS).text
        val_el = v.find("md:value", NS)
        if val_el is None or val_el.get(f"{{{NS['xsi']}}}nil") == "true":
            values.append((field, "null"))
            continue
        xtype = val_el.get(f"{{{NS['xsi']}}}type", "xsd:string")
        text = val_el.text or ""
        if xtype.endswith("boolean"):
            values.append((field, "true" if text == "true" else "false"))
        elif xtype.endswith(("double", "decimal", "int")):
            values.append((field, text))
        else:
            values.append((field, apex_str(text)))
    return full_name, label, values


def emit_chunk(records, out_path: Path):
    lines = [
        "// Generated by scripts/dev/generate-cmt-seed.py — do not edit.",
        "Metadata.DeployContainer c = new Metadata.DeployContainer();",
        "Metadata.CustomMetadata r;",
        "Metadata.CustomMetadataValue v;",
    ]
    for full_name, label, values in records:
        lines.append("r = new Metadata.CustomMetadata();")
        lines.append(f"r.fullName = {apex_str(full_name)};")
        lines.append(f"r.label = {apex_str(label)};")
        for field, literal in values:
            lines.append("v = new Metadata.CustomMetadataValue();")
            lines.append(f"v.field = {apex_str(field)};")
            lines.append(f"v.value = {literal};")
            lines.append("r.values.add(v);")
        lines.append("c.addMetadata(r);")
    lines.append("Id jobId = Metadata.Operations.enqueueDeployment(c, null);")
    lines.append("System.debug('Enqueued ' + jobId);")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(records)} records)")


def main():
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("cmt-seed-out")
    out_dir.mkdir(parents=True, exist_ok=True)
    src = Path(__file__).resolve().parents[2] / "force-app/main/default/customMetadata"
    parents, children = [], []
    for path in sorted(src.glob("*.md-meta.xml")):
        rec = parse_record(path)
        (children if rec[0].startswith("Humanitix_Field_Mapping.") else parents).append(rec)
    emit_chunk(parents, out_dir / "seed-00-parents.apex")
    for i in range(0, len(children), CHUNK):
        emit_chunk(children[i : i + CHUNK], out_dir / f"seed-{i // CHUNK + 1:02d}-fields.apex")
    print(f"total: {len(parents)} parent records, {len(children)} field mappings")


if __name__ == "__main__":
    main()
